# 1  write a program to create 3  by 3 identity metrix using numpy 

In [7]:
import numpy as np


identity_matrix = np.identity(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2 write a program to find a indices of the maximum and minimum value in a given array using numpy 

In [28]:
import numpy as np 
def find_max_value_index(x):
    max_index=np.where(x==x.max())
    return max_index

def find_min_value_index(x):
    min_index=np.where(x==x.min())
    return min_index


my_array= np.array([4,15,12,1])

maxvalue=find_max_value_index(my_array)
minvalue=find_min_value_index(my_array)

print(f"my array is {my_array}")
print(f"index of maximum value is {maxvalue}")
print(f"index of min value is {minvalue}")

my array is [ 4 15 12  1]
index of maximum value is (array([1]),)
index of min value is (array([3]),)


## 3. create a ID random array comprising elements in range 1 to 100. compute the minimum,maximum,mean,median,standard deviation,unique value,and count of unique value

In [13]:
import numpy as np 

# creating random data 
a = np.random.randint(1,100,50)


print(f"this is my data set{a}\n")

#minnimum value 
print("minimum value is :",a.min())

# maximum value 
print("maximum value is :",a.max())

# mean or avg
print(f" mean of the data is {a.mean()}")


# median

print(f"median of the data is {np.median(a)}")
# standard deviation 
print(f"std of the dataset is :{np.std(a)}")


#unique value
unique_data,count = np.unique(a,return_counts=True)

print(f"my unique dataset is :",unique_data)

# count of 


print("count of unique data",count.sum())            # not understand this 



this is my data set[71 28 43 75 25 59 76 61  1 25 33 90 30 73 87 84 99 26 88 62  1 22 15 66
 31 38  1 83 60 85 19 85  7 30 37 35 25 40 23  9 16  1 39 17 82 70  3 65
 62 36]

minimum value is : 1
maximum value is : 99
 mean of the data is 44.78
median of the data is 37.5
std of the dataset is :28.840450759306798
my unique dataset is : [ 1  3  7  9 15 16 17 19 22 23 25 26 28 30 31 33 35 36 37 38 39 40 43 59
 60 61 62 65 66 70 71 73 75 76 82 83 84 85 87 88 90 99]
count of unique data 50


# 4. write a program to create a shopping cart using a dictonary  in python .the program should allow users  to add items to the cart ,remove item from the cart ,and calculate the total price of all items in the cart 

In [25]:
class ShoppingCart:
    def __init__(self):
        self.cart = {}

    def add_item(self, item, quantity, price):
        if item in self.cart:
            self.cart[item] = (self.cart[item][0] + quantity, self.cart[item][1])
        else:
            self.cart[item] = (quantity, price)

    def remove_item(self, item):
        if item in self.cart:
            del self.cart[item]
        else:
            print("Item not found in cart")

    def calculate_total(self):
        total = 0
        for item in self.cart:
            quantity, price = self.cart[item]
            total += quantity * price
        return total

    def display_cart(self):
        for item in self.cart:
            quantity, price = self.cart[item]
            print(f"Item: {item}, Quantity: {quantity}, Price: {price}")


# Create an instance of the ShoppingCart class
shopping_cart = ShoppingCart()

# Add items to the cart
shopping_cart.add_item("Apple", 5, 0.99)
shopping_cart.add_item("Banana", 10, 0.50)
shopping_cart.add_item("Cherry", 3, 1.99)

# Display the cart
shopping_cart.display_cart()

# Calculate and display the total price of all items in the cart
total_price = shopping_cart.calculate_total()
print("Total Price: ", total_price)

# Remove an item from the cart
shopping_cart.remove_item("Cherry")

# Display the updated cart
shopping_cart.display_cart()

# Calculate and display the updated total price of all items in the cart
total_price = shopping_cart.calculate_total()
print("Updated Total Price: ", total_price)

Item: Apple, Quantity: 5, Price: 0.99
Item: Banana, Quantity: 10, Price: 0.5
Item: Cherry, Quantity: 3, Price: 1.99
Total Price:  15.919999999999998
Item: Apple, Quantity: 5, Price: 0.99
Item: Banana, Quantity: 10, Price: 0.5
Updated Total Price:  9.95


## 5, Write a Python program to create a new SQLite database and a table named &quot;students&quot; with columns for name, age, and grade.

In [8]:
import sqlite3


conn = sqlite3.connect(':memory:')

# Create a new table named "students" with columns for name, age, and grade

conn.execute('''
CREATE TABLE IF NOT EXISTS students (
    name TEXT,
    age INTEGER,
    grade REAL
)
''')

# Close the connection to the database
conn.close()



## 6. Give the output of the following python code consider mat as follows:
* mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
* a. mat[0]
* b. np.eye(3)*mat
* c. mat[1:, 1:]
* d. mat[: :-1] e. np.reshape(mat,(1,9))

In [5]:
import numpy as np 
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])

print("my array is \n\n",mat)


print("\n value of of mat[0] is : \n ",mat[0])


print(f"\n  value of np.eye(3)*mat is :\n  ",np.eye(3)*mat)


print("\n value of  mat[1:, 1:] is :\n ", mat[1:, 1:])


print("\nvalue of . mat[: :-1] is :\n ", mat[: :-1])

print(f"\nreshape(mat,(1,9) )is : \n ",np.reshape(mat,(1,9)))

my array is 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 value of of mat[0] is : 
  [1 2 3]

  value of np.eye(3)*mat is :
   [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]

 value of  mat[1:, 1:] is :
  [[5 6]
 [8 9]]

value of . mat[: :-1] is :
  [[7 8 9]
 [4 5 6]
 [1 2 3]]

reshape(mat,(1,9) )is : 
  [[1 2 3 4 5 6 7 8 9]]


## 7. Write one-liner codes in python to perform the following tasks. Assume numpy has been imported as np
* a. Create a 2D array called arr with random integers ranging from 10 to 35 with 4 rows and 5 columns.
* b. Transpose the above array.
* c. Divide each element in the above array by 5
* d. Calculate the mean of each row of the above array.
* e. Create a 2D array with all values as 8 as the same shape as in part b and add it to arr.
* f. Show all the values in arr less than 18


In [51]:
#  a. Create a 2D array called arr with random integers ranging from 10 to 35 with 4 rows and 5 columns.

import numpy as np 

np.random.seed(42)   # for same output of random no 

b=np.random.randint(10,35 ,size=(4,5))
print(f"my array is\n\n{b}\n")

# b b. Transpose the above array.


print(f"this is trasposed array \n \n {np.transpose(b)}\n")

#c. Divide each element in the above array by 5

divided_array=a/5

print(f"this is my divided arraY \n \n{divided_array}\n")

# d. Calculate the mean of each row of the above array.

print(f"row wise mean of my array data is",b.mean(axis=1))

my array is

[[16 29 24 20 17]
 [30 16 28 32 20]
 [20 33 30 13 17]
 [33 12 31 30 11]]

this is trasposed array 
 
 [[16 30 20 33]
 [29 16 33 12]
 [24 28 30 31]
 [20 32 13 30]
 [17 20 17 11]]

this is my divided arraY 
 
[[2.2 6.6 2.6 4.8 2.2]
 [6.2 3.4 5.2 4.8 3.8]
 [3.2 5.  5.2 3.  2.4]
 [4.6 6.8 4.6 6.4 4.2]]

row wise mean of my array data is [21.2 25.2 22.6 23.4]


In [4]:
# e. Create a 2D array with all values as 8 as the same shape as in part b and add it to arr.



import numpy as np


arr = np.random.randint(10, 36, size=(4, 5))

print("Original 2D Array:")
print(arr)


arr_8 = np.full_like(arr, fill_value=8)

print("\n2D Array with all values as 8:")
print(arr_8)


arr_sum = arr + arr_8

print("\nResultant 2D Array after adding the arrays:")
print(arr_sum)


# f. Show all the values in arr less than 18


filtered_value =arr[arr<18]
print("\nValues less than 18:")
print(filtered_value)

Original 2D Array:
[[29 26 32 10 32]
 [17 19 26 30 20]
 [35 16 29 17 30]
 [11 10 17 13 11]]

2D Array with all values as 8:
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]

Resultant 2D Array after adding the arrays:
[[37 34 40 18 40]
 [25 27 34 38 28]
 [43 24 37 25 38]
 [19 18 25 21 19]]

Values less than 18:
[10 17 16 17 11 10 17 13 11]
